printWidth: 100
singleQuote: true
semi: true
trailingComma: all
arrowParens: always
endOfLine: lf
overrides:
  - files:
      - '*.md'
      - '*.mdx'
    options:
      proseWrap: preserve
  - files: 'bin/*.js'
    options:
      trailingComma: es5
